name: Update Firestore Database

description: Update a field in firestore database

author: Emeka Orji

inputs:
  apiKey:
    description: Firebase API Key
    required: true
  authDomain:
    description: Firebase Auth Domain
    required: true
  databaseURL:
    description: Firebase Database URL
    required: true
  projectId:
    description: Firebase Project ID
    required: true
  storageBucket:
    description: Firebase Storage Bucket
    required: true
  messagingSenderId:
    description: Firebase Message Sender ID
    required: true
  appId:
    description: Firebase App ID
    required: true
  measurementId:
    description: Firebase Measurement ID
    required: true
  path:
    description: Path to what you want to set in your database
    required: true
  id:
    description: Id of the data
    required: true
  value:
    description: Value to be set
    required: false

outputs:
  response:
    description: 'The response from the firestore operation'

branding:
  icon: 'activity'
  color: 'gray-dark'

runs:
  using: 'node16'
  main: 'dist/index.js'