name: Update Firestore Database

description: Update a field in firestore database

author: Emeka Orji

inputs:
  credentials:
    description: Firebase Credentials
    required: true
  databaseUrl:
    description: Firebase Database URL
    required: true
  path:
    description: Path to what you want to set in your database
    required: true
  value:
    description: Value to be set
    required: false

outputs:
  response:
    description: 'The response from the firestore operation'

branding:
  icon: 'activity'
  color: 'gray-dark'

runs:
  using: 'node16'
  main: 'index.js'