name: Update Firestore Database

description: Update a field in firestore database

author: Emeka Orji

inputs:
  apiKey:
    description: API Key
    required: true
  authDomain:
    description: Auth Domain
    required: true
  databaseURL:
    description: Database URL
    required: true
  projectId:
    description: Project ID
    required: true
  storageBucket:
    description: Storage Bucket
    required: true
  messagingSenderId:
    description: Message Sender ID
    required: true
  appId:
    description: App ID
    required: true
  measurementId:
    description: Measurement ID
    required: true
  path:
    description: Path to what you want to set in your database
    required: true
  value:
    description: Value to be set
    required: false

outputs:
  response:
    description: 'The response from the firestore operation'

branding:
  icon: 'activity'
  color: 'gray-dark'

runs:
  using: 'node16'
  main: 'index.js'