---
name: Update Firestore Database

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    name: Install Dependencies

    steps:
      - uses: actions/checkout@master

      - name: Setup NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install Dependencies
        id: depsInstall
        run: npm install

      - name: Install Firebase Admin
        id: firebaseAdminInstall
        run: npm install firebase-admin --save

  notify:
    runs-on: ubuntu-latest
    name: Notify
    needs: [build]
    steps:
      - name: Update latest version in realtime database
        uses: w9jds/firebase-trigger@master
        with:
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          databaseUrl: ${{ secrets.FIREBASE_DATABASE_URL }}
          path: version/lastRelease