---
name: Update Firestore Database

on:
  push:
    branches:
      - master

jobs:
  databaseOperation:
    runs-on: ubuntu-latest

    name: Add data to Firestore Database

    steps:
      - uses: actions/checkout@master

      - name: Setup NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install Dependencies
        id: depsInstall
        run: npm install

      - name: Install Firebase Admin
        id: firebaseAdminInstall
        run: npm install firebase-admin --save

      - name: Push to Firestore Database
        id: updateFirebase
        uses: emekaorji/actions-demo@master
        with:
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          databaseUrl: ${{ secrets.FIREBASE_DATABASE_URL }}
          path: actions-demo/pushes
          value: ${{ github.ref }}

      - name: Get the response from the firestore operation
        run: echo "The response from the operation is ${{ steps.updateFirebase.outputs.response }}"